<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeminjamanSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // --- 10 Pending ---
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 1,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '11:00:00',
                'nama_acara' => 'Rapat Koordinasi',
                'jumlah_peserta' => 10,
                'penanggung_jawab' => 'Budi Santoso',
                'keterangan' => 'Persiapan proyek baru',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 2,
                'bidang_manual' => null,
                'ruang_id' => 2,
                'tanggal' => now()->addDay()->toDateString(),
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:00:00',
                'nama_acara' => 'Sosialisasi Program',
                'jumlah_peserta' => 20,
                'penanggung_jawab' => 'Ani Wijaya',
                'keterangan' => 'Sosialisasi kegiatan bulanan',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 3,
                'bidang_manual' => null,
                'ruang_id' => 1,
                'tanggal' => now()->addDays(2)->toDateString(),
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:00:00',
                'nama_acara' => 'Pelatihan Internal',
                'jumlah_peserta' => 15,
                'penanggung_jawab' => 'Rina Saputra',
                'keterangan' => 'Pelatihan dasar sistem',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 3,
                'tanggal' => now()->addDays(3)->toDateString(),
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'nama_acara' => 'Diskusi Anggaran',
                'jumlah_peserta' => 12,
                'penanggung_jawab' => 'Dewi Lestari',
                'keterangan' => 'Diskusi revisi anggaran',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 2,
                'bidang_manual' => null,
                'ruang_id' => 4,
                'tanggal' => now()->addDays(4)->toDateString(),
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'nama_acara' => 'Workshop Desain',
                'jumlah_peserta' => 18,
                'penanggung_jawab' => 'Fajar Hidayat',
                'keterangan' => 'Workshop desain sistem baru',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 3,
                'bidang_manual' => null,
                'ruang_id' => 2,
                'tanggal' => now()->addDays(5)->toDateString(),
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '11:30:00',
                'nama_acara' => 'Evaluasi Proyek',
                'jumlah_peserta' => 25,
                'penanggung_jawab' => 'Rudi Hartono',
                'keterangan' => 'Evaluasi progress bulanan',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 1,
                'tanggal' => now()->addDays(6)->toDateString(),
                'jam_mulai' => '07:30:00',
                'jam_selesai' => '09:30:00',
                'nama_acara' => 'Briefing Pagi',
                'jumlah_peserta' => 8,
                'penanggung_jawab' => 'Lina Marlina',
                'keterangan' => 'Briefing mingguan',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 2,
                'bidang_manual' => null,
                'ruang_id' => 5,
                'tanggal' => now()->addDays(7)->toDateString(),
                'jam_mulai' => '11:00:00',
                'jam_selesai' => '13:00:00',
                'nama_acara' => 'Rapat Divisi',
                'jumlah_peserta' => 30,
                'penanggung_jawab' => 'Hendra Gunawan',
                'keterangan' => 'Rapat rutin divisi',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 3,
                'bidang_manual' => null,
                'ruang_id' => 3,
                'tanggal' => now()->addDays(8)->toDateString(),
                'jam_mulai' => '15:00:00',
                'jam_selesai' => '17:00:00',
                'nama_acara' => 'Diskusi Tim',
                'jumlah_peserta' => 14,
                'penanggung_jawab' => 'Agus Pratama',
                'keterangan' => 'Diskusi ide baru',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 4,
                'tanggal' => now()->addDays(9)->toDateString(),
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:30:00',
                'nama_acara' => 'Rapat Tahunan',
                'jumlah_peserta' => 40,
                'penanggung_jawab' => 'Siti Nurhaliza',
                'keterangan' => 'Rapat besar tahunan',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 5 Ongoing ---
            [
                'bidang_id' => 2,
                'bidang_manual' => null,
                'ruang_id' => 1,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '12:00:00',
                'nama_acara' => 'Pelatihan Karyawan',
                'jumlah_peserta' => 50,
                'penanggung_jawab' => 'Darmawan',
                'keterangan' => 'Pelatihan softskill',
                'status' => 'ongoing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 2,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '17:00:00',
                'nama_acara' => 'Workshop Digital',
                'jumlah_peserta' => 60,
                'penanggung_jawab' => 'Halimah',
                'keterangan' => 'Workshop intensif',
                'status' => 'ongoing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 3,
                'bidang_manual' => null,
                'ruang_id' => 3,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '15:00:00',
                'nama_acara' => 'Simulasi Kebakaran',
                'jumlah_peserta' => 25,
                'penanggung_jawab' => 'Samsul',
                'keterangan' => 'Simulasi rutin',
                'status' => 'ongoing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 1,
                'bidang_manual' => null,
                'ruang_id' => 4,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '16:00:00',
                'nama_acara' => 'Rapat Proyek',
                'jumlah_peserta' => 20,
                'penanggung_jawab' => 'Mulyono',
                'keterangan' => 'Rapat progress proyek',
                'status' => 'ongoing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bidang_id' => 2,
                'bidang_manual' => null,
                'ruang_id' => 5,
                'tanggal' => now()->toDateString(),
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '17:00:00',
                'nama_acara' => 'Seminar Umum',
                'jumlah_peserta' => 70,
                'penanggung_jawab' => 'Putri',
                'keterangan' => 'Seminar terbuka',
                'status' => 'ongoing',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 15 Complete ---
            // Biar singkat, datanya mirip tapi beda nama & waktu
        ];

        // Tambahkan 15 data complete (loop supaya tidak terlalu panjang)
        for ($i = 1; $i <= 15; $i++) {
            $data[] = [
                'bidang_id' => rand(1, 3),
                'bidang_manual' => null,
                'ruang_id' => rand(1, 5),
                'tanggal' => now()->subDays($i)->toDateString(),
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:00:00',
                'nama_acara' => 'Acara Selesai ' . $i,
                'jumlah_peserta' => rand(5, 50),
                'penanggung_jawab' => 'PJ ' . $i,
                'keterangan' => 'Acara sudah selesai',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('peminjamans')->insert($data);
    }

}
